// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fybvrmhbzchivsyzylta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5YnZybWhiemNoaXZzeXp5bHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NjMwMTgsImV4cCI6MjA2MDEzOTAxOH0.NiMNNb-bNaQHZBQGKAbEm6hY-uaCxKW-dGsXKb32hak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);